version: '3'
services:
  #  server:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: server
  #    depends_on:
  #      - pg_db
  #      - redis_cache
  #    restart: always
  #    working_dir: /opt/app
  #    volumes:
  #      - ./:/opt/app
  #    ports:
  #      - 0.0.0.0:8000:8000
  #    networks:
  #      - server_network

  pg_db:
    image: postgres:12
    env_file:
      - ./.env.docker
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server_network

  pg_admin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.docker
    ports:
      - 5431:80
    networks:
      - server_network

  redis_cache:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    command: redis-server
    networks:
      - server_network

networks:
  server_network:
    driver: bridge

volumes:
  db-data:
  redis-data:
