version: "3"
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - pg_db
    restart: always
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
    ports:
      - 0.0.0.0:8000:8000
    networks:
    - server_network

  pg_db:
    image: postgres:12
    mem_limit: 1536MB
    mem_reservation: 1G
    env_file:
      - ./.env
    ports:
    - 0.0.0.0:8001:5432
    volumes:
    - db-data:/var/lib/postgresql/data
    networks:
    - server_network

  pg_admin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
    - 0.0.0.0:8002:80
    networks:
    - server_network

networks:
  server_network:
    driver: bridge

volumes:
  db-data: 
    bridge: local
